debug: false
application:
  container:
    image: docker-snapshot.cernerrepos.net/si-mapping/mapping-api:6.14.4:6.14.4
    reuse: false
  admin.enabled: false
client.repo:
  location: '${V1_URL}/api'
spring:
  config:
    import:
    - classpath:application-server.yml
    - optional:classpath:application.yml
  datasource:
    url: ${DB_URL}
    username: cm_jobs
    password: password
    container:
      image: docker-snapshot.cernerrepos.net/si-mapping/si-jobs-database:0.7.9
      reuse: false
    v1:
      username: cm_test
      password: password
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
  liquibase:
    enabled: false
    change-log: classpath:liquibase/changelog-test.xml
    contexts: test,xe,production
    dropFirst: false
logging:
  level:
    root: warn
    com.cerner: trace
    uk.co.blackpepper.bowman: trace
