spring:
  datasource:
    container:
      image: postgres:14.2
      config: '@project.build.directory@/classes/mysql.cnf'
      #port: 5432
    #url: jdbc:postgresql://localhost:5432/test
    username: test
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties.hibernate:
      jdbc.time_zone: UTC
