spring:
  main:
    banner-mode: 'off'
    allow-bean-definition-overriding: true
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    database-platform: org.hibernate.dialect.Oracle10gDialect
    properties.hibernate.jdbc.time_zone: UTC
  jersey:
    type: filter
    # applicationPath: /service
  liquibase:
    enabled: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:oracle:thin:@localhost:1521/XE
    username: test
    password: password
logging:
  sql:
    enabled: false
decorator:
  datasource:
    p6spy:
      multiline: true
      enable-logging: true
      logging: sysout
      log-format: '%(sql);'
      timestamp-format: 'yyyy-MM-dd HH24:MI:SS'
    enabled: true