spring:
  main:
    banner-mode: 'off'
    allow-bean-definition-overriding: true
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
       hibernate.jdbc.time_zone: UTC
       jdbc.lob.non_contextual_creation: true
       dialect: org.hibernate.dialect.PostgreSQLDialect
  jersey:
    type: filter
    # applicationPath: /service
  liquibase:
    enabled: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/testdb
    username: test
    password: password
decorator:
  datasource:
    p6spy:
      multiline: true
      enable-logging: true
      logging: sysout
      log-format: '%(sql);'
      timestamp-format: 'yyyy-MM-dd HH24:MI:SS'
    enabled: true