spring:
  datasource:
    type: org.apache.tomcat.jdbc.pool.DataSource
    tomcat:
      max-active: 2
      max-wait: 30
      max-idle: 2
      test-on-borrow: true
      validation-query: select 1 from dual
      validation-query-timeout: 30
  liquibase:
    enabled: false
test:
  containers:
    tomcat:
      reuse: false
      application:
        buildDir: '@project.build.directory@'
        warName: ROOT.war
        test:
          artifactId: '@project.artifactId@'
          version: '@project.version@'
    mrds:
      image: mysql:latest
      reuse: false      
      application:
        buildDir: '@project.build.directory@/test-classes'
      datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: test
        password: password
logging:
  level:
    liquibase: info
    liquibase.statement: warn
