server:
#  display-name: 'Test Service'
#  compression:
#    enabled: false
  #servlet.context-path: /service
  tomcat.accesslog:
    enabled: true
    basedir: target/tomcat
  port: '9080'
management:
  endpoints:
    web:
      base-path: /actuator
      exposure.include: '*'
  endpoint:
    shutdown.enabled: true
spring:
  config:
    import:
    - classpath:application-server.yml
    - classpath:mysql.yml
  liquibase:
    enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: test
    password: password
  jpa:
    open-in-view: true
#  application:
#    name: test-api
#logging:
#  level:
#    root: warn
#    "[org.springframework.transaction.interceptor]": warn
#    "[org.springframework.web]": info
#    "[org.hibernate]": warn
#    "[org.springframework.boot.web.embedded.tomcat.TomcatWebServer]": info