management:
  endpoints:
    web:
      base-path: /actuator
      exposure.include: '*'
  endpoint:
    shutdown.enabled: true
spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:
    # url: jdbc:oracle:thin:@test:1521/XE
    url: jdbc:mysql://mysql:3306/test
    username: test
    password: password
  application.admin.enabled: true
  liquibase:
    enabled: false
logging:
  level:
    root: warn
    com.cerner: info
